### ISSUE TITLE
Where do I put the code?

### ISSUE THREAD

**Issue by ioagentsmith** [The-Guide/fe-guild-2019-pwa-code-labs#1]
Please state that you need to add below to sw.js:

self.addEventListener('install', event => {
    console.log('[Service Worker] Installing Service Worker ...', event);
    event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating Service Worker ...', event);
    return self.clients.claim();
});

**Comment by raduenuca** [comment]
Fixed
